source :rubygems

gem "rack"

group :development, :test do
  gem "guard"
  gem "guard-rspec"
  gem "growl"
end

group :test do
  gem "rspec-core"
  gem "rspec-mocks"
  gem "rspec-expectations"
  gem "capybara", :git => 'git://github.com/jnicklas/capybara.git'
  gem "capybara-webkit"

  gem "syntax"

  gem "coffee-script"
  gem "iced-coffee-script-source", "1.2.0o"

  gem "jasmine-headless-webkit"
end
